---

- name: TEMPLATE | Template out the required files
  become: true
  become_user: root
  template:
    src: 'name.sudoers.d.j2'
    dest: "/etc/sudoers.d/{{ item | regex_replace('[%.!@#$%^&*]') }}"
    owner: "root"
    group: "root"
    mode: 'u=r,o=,g='
  with_items: "{{ linux_sudoers }}"

- name: FILE | Remove sudoers file created by azure
  become: true
  become_user: root
  file:
    path: "/etc/sudoers.d/90-cloud-init-users"
    state: absent
